# Generated by Django 4.0.1 on 2022-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabcontact',
            fields=[
                ('id_student', models.PositiveIntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=30)),
                ('number', models.IntegerField(max_length=30)),
                ('Email', models.EmailField(max_length=25)),
                ('section', models.CharField(max_length=25)),
                ('photos', models.FileField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
