# Generated by Django 4.0.1 on 2022-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcontact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabcontact',
            name='id_student',
        ),
        migrations.AddField(
            model_name='tabcontact',
            name='id',
            field=models.BigAutoField(auto_created=True, default=10000, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabcontact',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
    ]
