# Generated by Django 4.0.1 on 2022-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcontact', '0002_remove_tabcontact_id_student_tabcontact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabcontact',
            name='section',
        ),
        migrations.AddField(
            model_name='tabcontact',
            name='password',
            field=models.CharField(default=500, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabcontact',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tabcontact',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='media/photos'),
        ),
    ]
