# Generated by Django 4.0.1 on 2022-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcontact', '0003_remove_tabcontact_section_tabcontact_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabcontact',
            name='number',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tabcontact',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
